### ISSUE TITLE
Bigger content font on Simple Page and structure Page ?!

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-civic-europe#408]
**URL:** https://ce-dev.liqd.net/structered-text-page/
**important screensize:** *Both*
**device & browser:** *Safari and Chrome*
**Comment/Question:** *I know that this is a request from the client, but if the text box is bigger, I would at least make the paragraph text a bit bigger, but its fine if that's what they want. Usually, paragraphs should always have less than 90 characters per line. ^^

And here the section is overlapping the text*

<img width="989" alt="Screenshot 2021-02-16 at 12 13 20" src="https://user-images.githubusercontent.com/59610786/108056089-2035f100-7051-11eb-8683-2cc4054da6f6.png">

**Comment by fuzzylogic2000** [comment]
Yes, good comment! @hello-kathi Should we do something about it or do we do it just as they asked us and release and deploy like that?
We fixed the overlapping already by now.

**Comment by fuzzylogic2000** [comment]
Oh, haha! It was only broken styling because of another issue. So, the text is already bigger now! Could you have another look @mcastro-lqd ? Is it fine like it currently is?

**Comment by fuzzylogic2000** [comment]
No sorry, did just look bigger. It's still 14.4 px in both cases. :(
So, @hello-kathi what do we do?

**Comment by mcastro-lqd** [comment]
> Oh, haha! It was only broken styling because of another issue. So, the text is already bigger now! Could you have another look @mcastro-lqd ? Is it fine like it currently is?

**Comment by mcastro-lqd** [comment]
> No sorry, did just look bigger. It's still 14.4 px in both cases. :(

Yeah, it still shows 14.4pt to me, but as I said, if they want it wider, its also fine. 🤷‍♂️

**Comment by fuzzylogic2000** [comment]
Yes, cool, thanks! We will keep it like that because it's what they asked for and time is running out.
I will rename the issue and keep it, though. :)
